server:
  port: 0
  compression:
    enabled: true
  http2:
    enabled: true
  servlet:
    context-path: /
  tomcat:
    max-threads: 10
    min-spare-threads: 1
    connection-timeout: 20000

spring:
  application:
    name: micro-tracking

  web:
    cors:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

# Email donde recibir√°s las notificaciones
tracking:
  notification:
    email: ${TRACKING_NOTIFICATION_EMAIL:}

# Enlace con Resend
resend:
  api-key: ${RESEND_API_KEY:}
  from: "Portafolio <portafolio@javig.org>"
